version: "3.9"

services:
  password-locker:
    container_name: password-locker
    volumes:
      - /Users/davidhorvat/GolandProjects/password-lock:/app
    build:
      context: .
      dockerfile: Dockerfile
      target: debug
    ports:
      - "8085:8080"
      - "15850:2345"
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_NAME: "postgres"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"
    ports:
      - "5434:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
#    volumes:
#      - redis-data:/var/lib/redis/data

volumes:
  postgres-data:
    driver: local