version: "3.9"

services:
  password-lock:
    container_name: backend
    volumes:
      - /Users/davidhorvat/GolandProjects/password-lock:/app
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    ports:
      - "8085:8080"
      - "15850:2345"
    networks:
      - password-lock-backend-network
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_NAME: "postgres"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"
    ports:
      - "5434:5432"
    networks:
      - password-lock-backend-network
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - password-lock-backend-network

volumes:
  postgres-data:
    driver: local

networks:
  password-lock-backend-network:
    name: my-network
    driver: bridge